2014-05-04 22:51:14 Error: Fatal Error (4): syntax error, unexpected '.', expecting ',' or ';' in [/var/www/Remind-Me/app/Controller/UsersController.php, line 10]
2014-05-04 22:51:14 Error: [FatalErrorException] syntax error, unexpected '.', expecting ',' or ';'
Request URL: /Remind-Me/Users/login
Stack Trace:
#0 /var/www/Remind-Me/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/Remind...', 10)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/Remind...', 10, Array)
#2 /var/www/Remind-Me/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/Remind...', 10, Array)
#3 /var/www/Remind-Me/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-05-04 22:54:37 Error: Fatal Error (4): syntax error, unexpected '.', expecting ',' or ';' in [/var/www/Remind-Me/app/Controller/UsersController.php, line 10]
2014-05-04 22:54:37 Error: [FatalErrorException] syntax error, unexpected '.', expecting ',' or ';'
Request URL: /Remind-Me/Users/login
Stack Trace:
#0 /var/www/Remind-Me/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/Remind...', 10)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/Remind...', 10, Array)
#2 /var/www/Remind-Me/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/Remind...', 10, Array)
#3 /var/www/Remind-Me/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-05-04 22:54:54 Error: Fatal Error (4): syntax error, unexpected '.', expecting ',' or ';' in [/var/www/Remind-Me/app/Controller/UsersController.php, line 10]
2014-05-04 22:54:54 Error: [FatalErrorException] syntax error, unexpected '.', expecting ',' or ';'
Request URL: /Remind-Me/Users/login
Stack Trace:
#0 /var/www/Remind-Me/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/Remind...', 10)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/Remind...', 10, Array)
#2 /var/www/Remind-Me/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/Remind...', 10, Array)
#3 /var/www/Remind-Me/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-05-04 22:55:37 Error: Fatal Error (4): syntax error, unexpected '.', expecting ',' or ';' in [/var/www/Remind-Me/app/Controller/UsersController.php, line 10]
2014-05-04 22:55:37 Error: [FatalErrorException] syntax error, unexpected '.', expecting ',' or ';'
Request URL: /Remind-Me/Users/login
Stack Trace:
#0 /var/www/Remind-Me/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/Remind...', 10)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/Remind...', 10, Array)
#2 /var/www/Remind-Me/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/Remind...', 10, Array)
#3 /var/www/Remind-Me/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-05-04 22:58:25 Error: Fatal Error (4): syntax error, unexpected '.', expecting ',' or ';' in [/var/www/Remind-Me/app/Controller/UsersController.php, line 10]
2014-05-04 22:58:25 Error: [FatalErrorException] syntax error, unexpected '.', expecting ',' or ';'
Request URL: /Remind-Me/Users/login
Stack Trace:
#0 /var/www/Remind-Me/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/Remind...', 10)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/Remind...', 10, Array)
#2 /var/www/Remind-Me/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/Remind...', 10, Array)
#3 /var/www/Remind-Me/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
